/**
 * Bundled scores and backing tracks.
 *
 * The data — `bundledSongs.json`, `catalogIndex.ts`, `libraryEdition.ts` — is
 * generated by tools/build-library.ts from _MIDIS. This file is not: it is the
 * hand-written code that inflates that data, and the build never touches it.
 * Songs store one low, first-position cello line; easier levels are derived at runtime.
 */

import { CelloSongScore, CelloNote, CelloMeasure, DifficultyTier, measureDurationMs } from '@/domain/schema';
import { BackingTrack, BackingPart, InstrumentName, PartRole } from '@/domain/backing';
import { midiToPitchName, midiToFrequency } from '@/domain/cello';
import { firstPositionFingering } from '@/domain/fingering';
import rawData from './bundledSongs.json';


export interface CompactScoreDef {
  id: string;
  title: string;
  composer: string;
  origin: string;
  bpm: number;
  meter: [number, number];
  difficulty: DifficultyTier;
  /** Share of notes in [1st/half, 2nd-4th, 5th-thumb], as whole percents. */
  positions: [number, number, number];
  /** Detected key of the arranged line, e.g. "G major". Parsed, not just shown. */
  key: string;
  preferFlats: boolean;
  category: 'study' | 'classical' | 'song';
  notes: [number, number, number][];
  /** Held harmonic roots for the Beginner level. See tools/build-library.ts. */
  guide: [number, number, number][];
  /** Source bass/lower voice for Intermediate, on the same timeline. */
  bass: [number, number, number][];
  backingParts: [string, string, string, number, [number, number, number, number][]][];
}

export const COMPACT_SCORES: CompactScoreDef[] = rawData as CompactScoreDef[];

export function inflateScore(raw: CompactScoreDef): CelloSongScore {
  const barDurationMs = measureDurationMs(raw.meter, raw.bpm);
  const totalMs = Math.max(
    ...[raw.notes, raw.guide, raw.bass ?? []].map((line) =>
      line.reduce((max, n) => Math.max(max, n[1] + n[2]), 0)),
    ...raw.backingParts.map((part) => part[4].reduce((max, n) => Math.max(max, n[1] + n[2]), 0)),
  );
  const barCount = Math.max(1, Math.ceil(totalMs / barDurationMs));

  const measures: CelloMeasure[] = Array.from({ length: barCount }, (_, index) => ({
    index,
    startBarTimeMs: index * barDurationMs,
    durationMs: barDurationMs,
    timeSignature: raw.meter,
    tempoBpm: raw.bpm,
  }));

  // Hard first-position mapping: open strings cannot lose to solver weights.
  const solved = raw.notes.map(([midi]) => firstPositionFingering(midi));

  const notes: CelloNote[] = raw.notes.map(([midiNumber, startTimeMs, durationMs], i) => {
    const state = solved[i] ?? firstPositionFingering(midiNumber);
    const measureIndex = Math.min(barCount - 1, Math.floor(startTimeMs / barDurationMs));
    return {
      id: `${raw.id}-${i + 1}`,
      startTimeMs,
      durationMs: Math.max(1, Math.min(durationMs, barCount * barDurationMs - startTimeMs)),
      pitchName: midiToPitchName(midiNumber, raw.preferFlats),
      midiNumber,
      frequency: Math.round(midiToFrequency(midiNumber) * 100) / 100,
      string: state.string,
      finger: state.finger,
      position: state.position,
      extension: state.extension,
      articulation: 'arco',
      tie: false,
      measureIndex,
      bowDirection: i % 2 === 0 ? 'down' : 'up',
    };
  });

  return {
    schemaVersion: '1.0.0',
    id: raw.id,
    metadata: {
      title: raw.title,
      composer: raw.composer,
      origin: raw.origin,
      keySignature: raw.key,
      timeSignature: raw.meter.join('/'),
      bpm: raw.bpm,
      difficulty: raw.difficulty,
      tonic: raw.key.split(' ')[0] ?? 'C',
      preferFlats: raw.preferFlats,
      teaches: 'Low first-position cello. Beginner plays held bass anchors; Intermediate follows the bass; Advanced and Full carry the melody.',
      rights: raw.category === 'classical' ? 'Public domain' : raw.category === 'study' ? 'Original study' : 'Study reduction — personal practice, analysis and research',
    },
    measures,
    notes,
  };
}

export function inflateBacking(raw: CompactScoreDef): BackingTrack {
  const parts: BackingPart[] = raw.backingParts.map(([name, inst, role, gain, tNotes], idx) => ({
    id: `${raw.id}-p${idx}`,
    name,
    instrument: inst as InstrumentName,
    role: role as PartRole,
    gain,
    muted: false,
    notes: tNotes.map(([midiNumber, startTimeMs, durationMs, velocity]) => ({
      midiNumber,
      startTimeMs,
      durationMs,
      velocity,
    })),
  }));

  const durationMs = parts.reduce(
    (max, part) => part.notes.reduce((m, n) => Math.max(m, n.startTimeMs + n.durationMs), max),
    0,
  );

  return {
    id: raw.id,
    name: raw.title,
    source: 'imported',
    parts,
    bpm: raw.bpm,
    durationMs,
  };
}
