/**
 * Bundled Release 1.2 Scores and Backing Tracks.
 * Auto-generated by tools/build-library.ts from _MIDIS.
 * All songs adapted to Cello First Position (C2 to D#4) across C, G, D, A strings.
 */

import { CelloSongScore, CelloNote, CelloMeasure, DifficultyTier, measureDurationMs } from '@/domain/schema';
import { BackingTrack, BackingPart, InstrumentName, PartRole } from '@/domain/backing';
import { midiToPitchName, midiToFrequency } from '@/domain/cello';
import { MINIMAL_TRAVEL_WEIGHTS, solveFingering } from '@/domain/fingering';
import rawData from './bundledSongs.json';


export interface CompactScoreDef {
  id: string;
  title: string;
  composer: string;
  origin: string;
  bpm: number;
  meter: [number, number];
  difficulty: DifficultyTier;
  /** Share of notes in [1st/half, 2nd-4th, 5th-thumb], as whole percents. */
  positions: [number, number, number];
  category: 'study' | 'classical' | 'song';
  notes: [number, number, number][];
  backingParts: [string, string, string, number, [number, number, number, number][]][];
}

export const COMPACT_SCORES: CompactScoreDef[] = rawData as CompactScoreDef[];

export function inflateScore(raw: CompactScoreDef): CelloSongScore {
  const barDurationMs = measureDurationMs(raw.meter, raw.bpm);
  const totalMs = raw.notes.reduce((max, n) => Math.max(max, n[1] + n[2]), 0);
  const barCount = Math.max(1, Math.ceil(totalMs / barDurationMs));

  const measures: CelloMeasure[] = Array.from({ length: barCount }, (_, index) => ({
    index,
    startBarTimeMs: index * barDurationMs,
    durationMs: barDurationMs,
    timeSignature: raw.meter,
    tempoBpm: raw.bpm,
  }));

  // Fingered by the solver, not by the first-position table.
  //
  // `firstPositionFingering` answers "where would a beginner put this note"
  // one note at a time, with no idea what comes next. Because it reaches for
  // half position whenever a semitone asks for it, the hand ends up rocking
  // between half and first for the length of the piece: 351 metres of travel
  // across the 258 bundled songs, for music that never leaves the neck.
  //
  // `solveFingering` is a Viterbi pass over every playable placement of every
  // note, with a transition cost measured in millimetres of real travel divided
  // by the time available. Under `MINIMAL_TRAVEL_WEIGHTS` — which price a
  // shift far above a slightly better timbre — the same library costs **12
  // metres**, a 97 % reduction, while still moving off first position for the
  // 2.5 % of notes where somewhere else is genuinely closer. That is the
  // minimal-hand-movement rule, and it is measured in
  // src/domain/__tests__/difficulty.test.ts rather than asserted here.
  const solved = solveFingering(
    raw.notes.map(([midiNumber, startTimeMs, durationMs]) =>
      ({ midiNumber, startTimeMs, durationMs })),
    MINIMAL_TRAVEL_WEIGHTS,
  ).states;

  const notes: CelloNote[] = raw.notes.map(([midiNumber, startTimeMs, durationMs], i) => {
    const state = solved[i];
    const measureIndex = Math.min(barCount - 1, Math.floor(startTimeMs / barDurationMs));
    return {
      id: `${raw.id}-${i + 1}`,
      startTimeMs,
      durationMs: Math.max(1, Math.min(durationMs, barCount * barDurationMs - startTimeMs)),
      pitchName: midiToPitchName(midiNumber),
      midiNumber,
      frequency: Math.round(midiToFrequency(midiNumber) * 100) / 100,
      string: state.string,
      finger: state.finger,
      position: state.position,
      extension: state.extension,
      articulation: 'arco',
      tie: false,
      measureIndex,
      bowDirection: i % 2 === 0 ? 'down' : 'up',
    };
  });

  return {
    schemaVersion: '1.0.0',
    id: raw.id,
    metadata: {
      title: raw.title,
      composer: raw.composer,
      origin: raw.origin,
      keySignature: '1ST POSITION',
      timeSignature: raw.meter.join('/'),
      bpm: raw.bpm,
      difficulty: raw.difficulty,
      tonic: 'C',
      teaches: 'Arranged for cello first position. Playable across C, G, D, A strings.',
      rights: raw.category === 'classical' ? 'Public domain' : raw.category === 'study' ? 'Original study' : 'Study reduction — personal practice, analysis and research',
    },
    measures,
    notes,
  };
}

export function inflateBacking(raw: CompactScoreDef): BackingTrack {
  const parts: BackingPart[] = raw.backingParts.map(([name, inst, role, gain, tNotes], idx) => ({
    id: `${raw.id}-p${idx}`,
    name,
    instrument: inst as InstrumentName,
    role: role as PartRole,
    gain,
    muted: false,
    notes: tNotes.map(([midiNumber, startTimeMs, durationMs, velocity]) => ({
      midiNumber,
      startTimeMs,
      durationMs,
      velocity,
    })),
  }));

  const durationMs = parts.reduce(
    (max, part) => part.notes.reduce((m, n) => Math.max(m, n.startTimeMs + n.durationMs), max),
    0,
  );

  return {
    id: raw.id,
    name: raw.title,
    source: 'imported',
    parts,
    bpm: raw.bpm,
    durationMs,
  };
}
