/**
 * Which library this build carries. Generated by tools/build-library.ts — do
 * not edit by hand. Shown in the app so an installed build says what it is.
 */
export interface LibraryEdition {
  /** Widened on purpose: code that compares editions must compile in both builds. */
  id: 'full' | 'free';
  label: string;
  detail: string;
  bundledCount: number;
  songCount: number;
}

export const LIBRARY_EDITION: LibraryEdition = {
  "id": "full",
  "label": "Full library",
  "detail": "297 bundled pieces, including 284 arranged songs for personal practice",
  "bundledCount": 297,
  "songCount": 284
};
