#!/usr/bin/env bash
#
# Builds an installable release APK locally.
#
#   ./tools/build-apk.sh
#
# The APK is signed with the debug keystore Expo generates, which is fine for
# sideloading onto your own phone and not fine for the Play Store. For a store
# build, generate a real keystore and point `signingConfigs.release` at it.
#
# Two machine-specific things this script handles, both because of how this
# Mac is set up rather than anything about the app:
#
#   * JDK and Android SDK live under Homebrew, not in the usual places.
#   * The JVM cannot open outbound TCP connections here — every connect times
#     out, while Node and curl are fine — so Gradle is pointed at the local
#     Node proxy in tools/dev-proxy.mjs, which it reaches over loopback.
#
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PROXY_PORT="${PROXY_PORT:-8899}"

export JAVA_HOME="${JAVA_HOME:-/opt/homebrew/opt/openjdk@17}"
export PATH="$JAVA_HOME/bin:$PATH"
export ANDROID_HOME="${ANDROID_HOME:-/opt/homebrew/share/android-commandlinetools}"
export ANDROID_SDK_ROOT="$ANDROID_HOME"

if [ ! -d "$ANDROID_HOME/platforms" ]; then
  echo "No Android platforms in $ANDROID_HOME — run the sdkmanager install first." >&2
  exit 1
fi

if ! pgrep -f "tools/dev-proxy.mjs" > /dev/null; then
  echo "› starting dev proxy on 127.0.0.1:$PROXY_PORT"
  node "$ROOT/tools/dev-proxy.mjs" "$PROXY_PORT" &
  sleep 2
fi

if [ ! -d "$ROOT/android" ]; then
  echo "› no android/ directory — running prebuild"
  (cd "$ROOT" && npx expo prebuild --platform android)
fi

echo "sdk.dir=$ANDROID_HOME" > "$ROOT/android/local.properties"

# gradle.properties is regenerated by prebuild, so re-apply the two settings
# this machine and this target need. Building all four ABIs compiles the
# Reanimated and Worklets C++ four times and races reanimated's lint-AAR task
# against CMake output for the other architectures.
PROPS="$ROOT/android/gradle.properties"
if ! grep -q "^reactNativeArchitectures=arm64-v8a$" "$PROPS"; then
  sed -i '' 's/^reactNativeArchitectures=.*/reactNativeArchitectures=arm64-v8a/' "$PROPS"
fi
if ! grep -q "systemProp.https.proxyHost" "$PROPS"; then
  cat >> "$PROPS" <<PROPEOF

systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=$PROXY_PORT
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=$PROXY_PORT
systemProp.http.nonProxyHosts=localhost|127.0.0.1
PROPEOF
fi

# The wrapper's own JVM downloads the Gradle distribution, so it needs the
# proxy too; the daemon reads the systemProp.* entries in gradle.properties.
export GRADLE_OPTS="-Dhttp.proxyHost=127.0.0.1 -Dhttp.proxyPort=$PROXY_PORT -Dhttps.proxyHost=127.0.0.1 -Dhttps.proxyPort=$PROXY_PORT -Dhttp.nonProxyHosts=localhost|127.0.0.1"

cd "$ROOT/android"
./gradlew assembleRelease --no-daemon "$@"

APK="$ROOT/android/app/build/outputs/apk/release/app-release.apk"
if [ -f "$APK" ]; then
  echo
  echo "APK: $APK"
  ls -lh "$APK" | awk '{print "     " $5}'
else
  echo "Build finished but no APK at $APK" >&2
  exit 1
fi
